#ifndef DEFINES_H
#define DEFINES_H

#define END_OF_SHIFT                21

#define INCOMPLETE_DAY_HEX  "#b5b5b5"
#define FINISHED_DAY_HEX    "#808080"
#define PAYED_DAY_HEX       "#00aa00"

#define DB_TABLE_EMPLOYEE_NAME      0
#define DB_TABLE_EMPLOYEE_SALARY    1
#define DB_TABLE_EMPLOYEE_COLOR     2
#define DB_TABLE_EMPLOYEE_ID        3

#define DB_TABLE_DAYS_DATE          0
#define DB_TABLE_DAYS_EMPLOYEE      1
#define DB_TABLE_DAYS_ISFINISHED    2
#define DB_TABLE_DAYS_ISPAYED       3
#define DB_TABLE_DAYS_SALARY        4
#define DB_TABLE_DAYS_POINT_ID      5

#define DB_TABLE_POINTS_ID          0
#define DB_TABLE_POINTS_NAME        1
#define DB_TABLE_POINTS_MARKET      2
#define DB_TABLE_POINT_EMPLOYEE1    3
#define DB_TABLE_POINT_EMPLOYEE2    4
#define DB_TABLE_POINT_OPEN_DATE    5
#define DB_TABLE_POINT_START_DATE   6
#define DB_TABLE_POINT_LAST_PAYDAY  7
#define DB_TABLE_POINT_SCHEDULE     8

#endif // DEFINES_H
