#ifndef DEFINES_H
#define DEFINES_H

#define DB_TABLE_EMPLOYEE_NAME      0
#define DB_TABLE_EMPLOYEE_SALARY    1
#define DB_TABLE_EMPLOYEE_COLOR     2

#define DB_TABLE_DAYS_DATE          0
#define DB_TABLE_DAYS_EMPLOYEE      1
#define DB_TABLE_DAYS_ISFINISHED    2
#define DB_TABLE_DAYS_ISPAYED       3
#define DB_TABLE_DAYS_SALARY        4

#endif // DEFINES_H
